version: "3.9"

services: 
  web:
    container_name: web_client
    build: 
      context: ./web
    env_file: 
      - "./web/.env"
    ports: 
      - 3000:3000
    volumes:
      - ./web/:/usr/app/

