import Head from 'next/head'
import Image from 'next/image'
import HelloWorld from '../components/HelloWorld'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Workplanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <HelloWorld />
      </main>
    </div>
  )
}
