import Head from 'next/head'
import Image from 'next/image'
import Hello from '../components/hello'

export default function hello() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Hello />
      </main>
    </div>
  )
}
